### ISSUE TITLE
Feature request: Sparse Git checkout

### ISSUE THREAD

**Issue by dergraf** [code-supply/deps_nix#2]
Hi there

Filing this and likely some other issues, referencing some of the missing features.

I had a variant of the sparse checkout working by manually adding a preBuild step that deleted all the unused folders. To my knowledge Nix has support for sparse Git checkouts, but I didn't manage to make this work using deps_nix. 

I am quite new to Nix, so there's likely my lack of knowledge involved here as well.

**Comment by camelpunch** [comment]
Could you maybe describe your motivation for needing sparse checkouts, so we can address this? If you no longer believe you need it, please close. Cheers!
