### ISSUE TITLE
Feature request: Dependencies that use Makefile (e.g. erlang.mk)

### ISSUE THREAD

**Issue by dergraf** [code-supply/deps_nix#3]
Another missing feature.

Mix is aware of dependencies that use Makefiles, which is quite popular in the Erlang space, where erlang.mk is a popular alternative to rebar3.
I've seen that Mix will just build it, without actually adding the "make" builder to the lock item. As a result the deps_nix generator will treat it as a dependency that can be built with Elixir using `buildMix`. However `buildMix` expects a `Mix.Project ` to be available in the dependency. I guess it would make sense to have another strategy that is able to deal with the situation.

I will try to contribute something to this or #2  issue.

Cheers,
Andre

**Comment by camelpunch** [comment]
Yeah I’ve deliberately not included Make builder code yet, pending some examples. Do you have packages in mind?

I’ve considered a slow test that iterates over everything in Hex, which could flush this sort of thing out.
